rougier/freetype-gl

CMakeLists.txt

I'm building freetype-gl as part of a parent CMake project. This project also builds freetype and glew, whose headers and built libraries are therefore available when freetype-gl is built, removing the need for the required option in the FIND_PACKAGE commands.
My proposal is to allow the user of freetype-gl to choose whether the libraries are required on the system, or will be passed in as part of a parent build. The default will of course remain as is currently.
Here is a snippet from my CMakeLists.txt demonstrating the change:
```cmake
OPTION(glew-cmake_BUILD_SHARED "Build the shared glew library" OFF)
ADD_SUBDIRECTORY(lib/glew)
SET(GLEW_INCLUDE_PATH "${MAINFOLDER}/lib/glew/include")
ADD_SUBDIRECTORY(lib/freetype2)
SET(FREETYPE_INCLUDE_DIRS "${MAINFOLDER}/lib/freetype2/include") …
```

Allow required libs to be supplied by parent build

---

CMakeLists.txt

This allows to compile freetype-gl with or without support for Vertex
Array Objects, which are a requirement for forward compatible OpenGL
3.0+ contexts.
This fixes #57.

Expose the FREETYPE_GL_USE_VAO definition as CMake option

---

text-buffer.c
text-buffer.h

I'm working on an OSX app and I'd like to be able to bundle the text_buffer vert/frag shaders in the app itself. Since the shader paths are currently hardcoded in text-buffer.c I implemented a second new method that allows for custom shader paths to be passed.
* added text_buffer_new_with_shaders() function
* call text_buffer_new_with_shaders() from text_buffer_new() using original text shader paths

Updated text-buffer to allow for custom shaders.

---

makefont.c
markup.h
shaders/text.frag
shaders/text.vert
text-buffer.c
text-buffer.h
vertex-buffer.c

vertex-buffer, text-buffer: restore modified OpenGL states after rendering.
makefont: allow arbitrary texture sizes instead of the default 128x128 to build embedded textures of higher resolution.
text-buffer: specifying filenames of shaders prevents the use of embedded shaders, this is resolved by allowing the user to build the embedded shader and provide a linked GLSL program instead.

Restore OpenGL state, higher resolution embedded fonts, and externally linked GLSL program

---

opengl.h
texture-atlas.c

Fix GLES 2 support - GL_RED does not exist in GLES 2.
When freetype-gl is built, neither the macro ```GL_ES_VERSION_3_0``` nor ```GL_ES_VERSION_2_0``` is ever set. Counterintuitively, these get set in ```<OpenGLES/ES3/gl.h>``` and ```<OpenGLES/ES2/gl.h>```. Therefore I've added a custom preprocessor macro that can be set as part of the build process ```FREETYPE_GL_ES_VERSION_3_0``` which will force GLES3 for iOS if it is set. Otherwise, builds for iOS will fall back to GLES2.

Add GLES 3 support for iOS.

---

CMakeLists.txt

The use case is that glfw is not installed on the machine and is being built as part of the parent build process. The default is the same as the current setting - to require glfw libraries.
An example of how to do this from the parent CMakeLists.txt:
```
OPTION(GLFW_BUILD_EXAMPLES "Build the GLFW example programs" OFF)
OPTION(GLFW_BUILD_TESTS "Build the GLFW test programs" OFF)
OPTION(GLFW_BUILD_DOCS "Build the GLFW documentation" OFF)
OPTION(GLFW_INSTALL "Generate installation target" OFF)
ADD_SUBDIRECTORY(lib/glfw)
OPTION(freetype-gl_BUILD_DEMOS "Build the freetype-gl example programs" OFF)
OPTION(freetype-gl_BUILD_APIDOC "Build the freetype-gl API documentation" OFF)
OPTION(freetype-gl_LIBS_SUPPLIED "Required libraries are supplied as part of parent build" ON) …
```

Make glfw optional so that it can be provided by parent build

---

texture-atlas.c

Currently text is not displayed when using GLES3. This is because the call to glTexImage2D is incorrect: ```GL_LUMINANCE``` is used for GLES2 and ```GL_RED``` for GLES3. [According to the documentation][1] for this function in GLES 3, ```GL_LUMINANCE``` should be used.
This condition was added by my PR (https://github.com/rougier/freetype-gl/pull/80) but only covered GLES2.
[1]: https://www.khronos.org/opengles/sdk/docs/man3/html/glTexImage2D.xhtml

Fixes text not displaying in GLES3

---

vertex-buffer.c

I moved on to using vertex_buffer in my app to dynamically add/remove characters and was getting a crash when calling vertex_buffer_erase(). This was due to an incorrect assert in vertex_buffer_erase_vertices(). The assert was assuming that 'last' was a length and doing (first+last) <= size. 'last' is an already calculated index and thus the assert should actually be last < size.
I've made this change and can confirm that vertex_buffer_erase_vertices() (and by extension vertex_buffer_erase()) now works as expected.

Updated vertex-buffer.c, fixed incorrect assert in vertex_buffer_erase_vertices()

---

CMakeLists.txt
demos/ansi.c
demos/atb-agg.c
demos/benchmark.c
demos/cartoon.c
demos/console.c
demos/distance-field-2.c
demos/distance-field-3.c
demos/distance-field.c
demos/embedded-font.c
demos/font.c
demos/gamma.c
demos/glyph.c
demos/lcd.c
demos/markup.c
demos/outline.c
demos/subpixel.c
demos/texture.c
doc/documentation.h
font-manager.c
font-manager.h
makefont.c
text-buffer.c
text-buffer.h
texture-font.c
texture-font.h
utf8-utils.c
utf8-utils.h

This pull requests removes the use of any wchar_t related functions and API interfaces in favor of UTF-8 encoded strings as already suggested/requested in the issues #6 and #69.  Functions now accept UTF-8 encoded char * strings instead of wchar_t * string with an undefined encoding.
To avoid additional allocation and freeing of memory blocks for the glyphs and kernings I have chosen to use uint32_t with an UTF-32 LE encoding as codepoint attributes.  This also improves readability of the code in comparison to an UTF-8 encoded codepoint in the glyph and kerning structs.
Most of the demos use only the ASCII subset (which is compatible with UTF-8) so I didn't add any dependencies to the Unicode functions header if not necessary.

Use UTF-8 encoded parameters for the various public functions

---

texture-font.c

Fixed two memory leaks in texture_font_load_glyph where the FT_Face and FT_Library initialised by texture_font_load_face aren't cleaned up.

Fixed Memory Leaks

---

CMakeLists.txt
CMakeModules/FindAntTweakBar.cmake
INSTALL.md
demos/markup.c

For context see #133 
The changes in this PR differ slightly from the ones described in the original issue.
- Link MATH_LIBRARY only if found
- Add support for msys2 MINGW64 based builds on Windows
- Add install & build instructions to INSTALL.md
- Add compiler flags for mingw builds to CMakeLists.txt
- Check for `__MINGW32__` in markup.c so that no error is printed
- Change FindAntTweakBar.cmake to find appropriate library for 32 or 64-bit
- Change harfbuzz examples to not use symlinks
- Check if GLFW3_LIBRARY is defined before linking, alternatively use glfw for linking (I ran into the same problem as described in  #124 and tried to come up with a reasonable fix)
Note: Symlinks are not deleted yet, but harfbuzz examples are changed to not use them anymore.
I was only able to test on …

Add support for building with msys2 mingw

---

INSTALL.md

I figured the dependencies from the cmake errors. It's possible that there are dependencies that I already had installed and therefore I didn't know those could be missing from the list.

Add macOS installation instructions

---

demos/cube.c

The cube demo is different than the others in that there's no text in it. Removing the redundant include makes that more clear / less confusing.

cube demo: remove unused include

---

demos/cube.c
demos/distance-field-2.c
demos/distance-field-3.c
demos/distance-field.c

Fixes https://github.com/rougier/freetype-gl/issues/91 for the vector-graphics demos.
Before the fix, on retina display the demo appears on the lower left part of the window until moving the window, which makes it become the right size.

Fix #91 for cube and distance-field demos

---

demos/ansi.c
demos/atb-agg.c
demos/console.c
demos/gamma.c
demos/markup.c
demos/outline.c
demos/subpixel.c
markup.h

There's no support for it since f83aae3389b5ddaab56342a050828591baeb9899, so it may just cause confusion and mislead.

remove "rise" field from markup_t

---

font-manager.c

The `file_exists` function in `font-manager.c` isn't marked `static`, even though it is internal to that file and does not have a prefixed name, so it can easily clash with other functions of the same name. Not only it can clash but reportedly when creating Haskell bindings for freetype-gl it indeed does clash with a function of the same name from ghc's Win32Utils.
I didn't find other such functions with are not exposed in the header file or their names are unprefixed which aren't static - this appears to be the only one.

add missing static keyword to internal function file_exists

---

demos/atb-agg.c

Currently the text disappears when changing the secondary weight to zero,
due to weights being [0, 0, 256, 0, 0] overflowing to [0, 0, 0, 0, 0].

demos/atb-agg: fix off-by-one bug in weights calculation

---

demos/atb-agg.c

The colors which are set in the "display" function have no effect.
A programmer may try to change the color there and not understand why nothing happens..

demos/atb-agg: remove misleading code which does nothing

---

texture-font.h

This allows the user to know when the font atlas really changed on a glyph request and therefore, if he needs to update his GL texture.
This avoids the unnecessary GL texture updates required with texture_font_get_glyph, which doesnt let the user know whether the glyph was "loaded" or "found" to use ftgls terminology, and therefore, if his GL texture requires an update.
As the methods implementation is already present and used internally inside texture_font_get_glyph, this should be a free performance gain for the user, just by allowing this slightly finer degree of control.
User code could look something like this:
texture_glyph_t* glyph_ptr = texture_font_find_glyph(users_texture_font, &users_required_character);
if(!glyph_ptr) {
//glyph not found, must load it …

Exposed texture_font_find_glyph to the API

---

texture-font.c
texture-font.h

Added the method texture_font_enlarge_atlas which allows resizing of the texture atlas while keeping all existing glyphs validated. 
Unfortunately it has to be part of the texture_font_t "class" as the glyphs' uvs need to be updated.

Added Feature to Enlarge the Texture atlas

---

text-buffer.c

In `text_buffer_add_text`, for each code-point `utf8_strlen` is called, causing quadratic performance instead of linear, as well as a memory read outside the buffer for strings that are provided with an explicit length instead of null termination. The fix is simply to use the provided (or previously calculated) `length`.

Fix buffer over-read and performance bug

---

texture-font.c

`texture_font_load_glyphs()` is incorrectly processing the passed in `codepoints` list.
It increments the index offset by each codepoint length correctly, but is using that *bytecount* as a *codepoint count*.
Thus it stops processing when it has read `utf8_strlen(codepoints)` bytes, not `utf8_strlen(codepoints)` glyphs. So if your codepoint list had 147 codepoints, only 147 bytes were being consumed.

Fix loading of codepoints. 

---

texture-font.c
texture-font.h

Just wrote a simple code addition that gives support for configuring padding that will be added to glyphs while they are loaded by its font.
It can be useful.

 Add support for padding configuration

---

harfbuzz/CMakeLists.txt
harfbuzz/platform.c

Fix to point 2 of #211; this solution was described in the issue as well.

Fixed Windows Harfbuzz build by adding platform.c to source files.

---

makefont.c

I made a few improvements and fixes to `makefont.c` including fixing this issue: https://github.com/rougier/freetype-gl/issues/187

Makefont improvements

---

distance-field.c

There is a small typo in distance-field.c.
Should read `minimum` rather than `minimimum`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, minimimum -> minimum

---

texture-font.c

With this, the maximum font size without overflow is 1023.
Reducing HRES to 1 raises that to 65535.

Remove 100x font scaling that caused overflow. Fix #210

---

CMakeLists.txt
font-manager.c
freetype-gl.h
ftgl-utils.c
ftgl-utils.h
text-buffer.c
texture-atlas.c
texture-font.c
texture-font.h
vector.c
vertex-attribute.c
vertex-buffer.c

Provide C-style callback function to call on error.
* default behaviour left unchanged (stream to `stderr`)
* expose logging output to end-user with `set_error_callback()`
Added this as `ftgl-utils` source files, since wasn't sure where else to place it, as there isn't any existing common header shared in codebase.
References rougier/freetype-gl#241

Provide means to change on error behaviour

---

texture-font.c

Fixes/code style changes around `FT_Error_String()`, adresses:
* update comments/placements of defines to make more sense scope-wise and make function more readable (as this could easily break, when someone unsuspecting moves these defines around)
* used define macro, which has been only recently changed, causing it not to work as intended with library shipped in `windows/freetype` which is an older version
* do not use reserved FT_Error_String() name as it may clash with freetype libraries (see [documentation](https://www.freetype.org/freetype2/docs/reference/ft2-error_enumerations.html#FT_Error_String))
References #244

FT_Error_String() fixes

---

demos/ansi.c
demos/atb-agg.c
demos/gamma.c
demos/lcd.c
demos/markup.c
demos/subpixel.c

`glBlendColor` only has an effect when using `glBlendFunc` with
`GL_CONSTANT_COLOR`, `GL_ONE_MINUS_CONSTANT_COLOR`, `GL_CONSTANT_ALPHA`, or `GL_ONE_MINUS_CONSTANT_ALPHA`.
(according to https://www.opengl.org/sdk/docs/man4/html/glBlendFunc.xhtml).
As these blend funcs aren't used anywhere, the calls to `glBlendColor` are misleading,
and someone looking to learn from these examples might end up quite confused.

Remove calls to glBlendColor which do nothing

---

.gitignore
CMakeLists.txt
ftgl-utils.h

After #169 was merged in some issues raise up in the projects I'm working on. So I had to do some fixes
~~- move libraries from global scope to freetype-gl target for dependency use~~
~~- silence warnings of cmake policy due support for older cmake~~
~~- remove debug build flag, invoker should provide that flag global~~
~~- move defines to freetype-gl target from global list~~
~~- fix missing bracket in ftgl-utils header~~
Ended up reverting the changes I did to the cmake as tests failed. I cannot run tests on my side as the default build doesn't link so it's hard to debug where the issue is. For now it would be great if atleast this could get merged in order to make things compile again.

Update CMakeLists.txt to use targets more correctly

---

harfbuzz/texture-font.h

This is a quick bugfix to remove a redundant `rendermode_t` definition from `texture-font.h`

remove redundant rendermode_t def from texture-font.h

---

texture-font.c
texture-font.h

Hello,
Here is a ready to merge pull request that fixes a double deletion crash!
I had a crash inside texture_glyph_delete () when iterating over `for(i=0; i < self->kerning->size; i++)` because the `self->kerning` vector was already freed.
The issue was that the `vector_t* kerning` was duplicated via a simple `memcpy()` in `texture_font_load_glyph_gi()`, instead of making a real copy of the vector.
This pull request introduces a new function `texture_glyph_clone()` that performs a deep copy of the glyph, _i.e._ it explicitly clones the kerning vector.
Note that this is still imperfect, because there is another location where glyphs are duplicated with `memcpy()`, which is inside 
`texture_font_index_glyph()`. I must admit, I'm not totally confident with the `texture_glyph_t ***` triple …

Fix double deletion of glyph kerning vector

---

CMakeLists.txt
opengl.h

also add predefine macro to prevent include glew.h while build without GLEW
build pass with command
```
cmake .. -Dfreetype-gl_BUILD_DEMOS=OFF -Dfreetype-gl_BUILD_TESTS=OFF -Dfreetype-gl_OFF_SCREEN=ON -Dfreetype-gl_BUILD_SHARED=ON -Dfreetype-gl_WITH_GLEW=OFF
make
```

add support for off-screen render at linux without glx

---

demos/embedded-font.c
makefont.c

The data structures generated by makefont are not valid, and may fail
to compile depending on compiler flags:
error: missing braces around initializer [-Werror=missing-braces]
| texture_glyph_t font_glyph_00000020 =   {32, 2, 2, 0, 0, 9.640625f
|                                         ^
The texture_glyph_t::kerning field is a double array, so it is invalid
to initialize it as an integer, "0". When a glyph has no kerning
pairs, initialize the "kerning" field to "{{0}}".
Remove the "texture_glyph_0x100_t" structure and incorporate the
glyphs pointer array directly into texture_font_t.

makefont: Fix invalid C data structures declarations

---

text-buffer.c
text-buffer.h

Currently compiling simple main.c which includes text-buffer.h using clang with -Werror and -Wstrict-prototypes results in error with the following message:
```
error: a function declaration without a prototype is deprecated in all versions of C
```
Putting a simple void fixes the problem.

Added missing 'void' in text_buffer_new function

---

INSTALL.md

Hi, freetype-gl can be installed on Arch Linux with the PKGBUILD on the Arch User Repository.

Add AUR link in INSTALL.md

---

makefont.c

`u` instead of `d` because `size_t` is an unsigned integer, and `z` is the appropriate length modifier according to the [manual](https://man7.org/linux/man-pages/man3/printf.3.html). This fixes the associated compiler warnings.

Minor fixes to fprintf calls

---

distance-field.c

`unsigned int` might be smaller than `size_t` (e.g. on Linux x86_64), in which case the multiplication might overflow, leading to too small malloced memory areas. Fix this by casting to size_t before multiplication.

Ensure no integer overflow in malloc and calloc
